# Generated by Django 3.2.23 on 2024-03-19 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_stock_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
